- name: restart apache and mariadb service
  hosts:  ansible-c07-vm2
       
  tasks: 
    - name: 
      yum:
          name: httpd, mariadb-server
          state: latest 
      notify:
        - restart_httpd
        - restart_mariadb 

  handlers:
      - name: restart_httpd
        systemd:
          name: httpd
          state: restarted 
          enabled: true 
      - name: restart_mariadb 
        systemd:
          name: mariadb
          state: restarted 
          enabled: true    
      - name: status of both services 
        shell:
            systemctl status httpd 
            systemctl status mariadb